export const SET_TODO: string = 'SET_TODO'
export const SET_TODO_LIST: string = 'SET_TODO_LIST'
export const REMOVE_TODO_LIST: string = 'REMOVE_TODO_LIST'
export const SET_TODO_STATUS: string = 'SET_TODO_STATUS'
export const SET_TODO_DOING: string = 'SET_TODO_DOING'